# Generated by Django 3.2.8 on 2021-10-27 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriversLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('owner_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.carowner')),
            ],
        ),
    ]
