# Generated by Django 3.2.8 on 2021-10-28 14:01

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('djangoApp', '0002_driverslicense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carowner',
            old_name='birth_data',
            new_name='birth_date',
        ),


    ]
