# Generated by Django 3.2.8 on 2021-10-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0005_auto_20211029_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='members',
            field=models.ManyToManyField(through='djangoApp.Ownership', to='djangoApp.CarOwner'),
        ),
    ]
