# Generated by Django 3.2 on 2022-01-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='group',
            field=models.CharField(blank=True, choices=[('1-A', '1-A'), ('1-B', '1-B'), ('2-A', '2-A'), ('2-B', '2-B'), ('3-A', '3-A'), ('3-B', '3-B')], max_length=4),
        ),
        migrations.AlterField(
            model_name='homework',
            name='penalty_info',
            field=models.CharField(max_length=100),
        ),
    ]
