# Generated by Django 3.2 on 2022-01-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0002_auto_20220115_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcompletion',
            name='mark',
            field=models.CharField(choices=[('-', '-'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='-', max_length=1),
        ),
    ]
