# Generated by Django 3.2 on 2022-01-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0003_alter_taskcompletion_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcompletion',
            name='group',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='task_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
