# Generated by Django 3.2 on 2022-01-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0004_auto_20220121_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcompletion',
            name='group',
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='subject',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
