# Generated by Django 4.0.1 on 2022-01-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Unique id of city')),
                ('name', models.CharField(max_length=100, verbose_name='City name')),
                ('country', models.CharField(max_length=100, verbose_name='Coutry code')),
                ('country_verbose', models.CharField(max_length=100, verbose_name='Country name')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
            ],
        ),
    ]
