# Generated by Django 4.0.1 on 2022-01-17 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('race_winners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentator',
            old_name='rating',
            new_name='raiting',
        ),
    ]
