# Generated by Django 4.0 on 2022-01-15 17:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Номер кабинета')),
                ('phone_number', models.IntegerField(default=0, verbose_name='Внутренний телефон')),
            ],
        ),
        migrations.CreateModel(
            name='CabinetOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=120, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='Имя доктора')),
                ('last_name', models.CharField(max_length=120, verbose_name='Фамилия доктора')),
                ('education', models.CharField(choices=[('bch', 'bachelor'), ('phd', 'Ph.D.')], max_length=120, verbose_name='Образование')),
                ('sex', models.CharField(choices=[('f', 'female'), ('m', 'male')], max_length=120, verbose_name='Пол')),
                ('date_of_birth', models.DateField(verbose_name='День рождения')),
                ('date_of_start', models.DateField(verbose_name='День начала работы в клинике')),
                ('date_of_end', models.DateField(blank=True, null=True, verbose_name='День конца работы в клинике')),
                ('contract', models.CharField(max_length=120, verbose_name='Данные по договору')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='Имя пациента')),
                ('last_name', models.CharField(max_length=120, verbose_name='Фамилия пациента')),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=120, verbose_name='Название услуги')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название специализации')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата приема')),
                ('diagnose', models.CharField(max_length=120, verbose_name='Диагноз')),
                ('current_status', models.TextField(verbose_name='Текущее состояние больного')),
                ('recommendation', models.TextField(verbose_name='Рекомендации по лечению')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.cabinet', verbose_name='Кабинет')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.doctor', verbose_name='Доктор')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.patient', verbose_name='Пациент')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.pricelist', verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='VisitOfPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.medicalcard', verbose_name='Мед карта')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.patient', verbose_name='Пациент')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.visit', verbose_name='График работы')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleOfDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(blank=True, choices=[('mon', 'monday'), ('tue', 'tuesday'), ('wed', 'wednesday'), ('thu', 'thursday'), ('fri', 'friday'), ('sat', 'saturday'), ('sun', 'sunday')], default=None, max_length=120, verbose_name='День недели')),
                ('status', models.BooleanField(default=0, verbose_name='Статус')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.doctor', verbose_name='Доктор')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleOfCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(blank=True, choices=[('mon', 'monday'), ('tue', 'tuesday'), ('wed', 'wednesday'), ('thu', 'thursday'), ('fri', 'friday'), ('sat', 'saturday'), ('sun', 'sunday')], default=None, max_length=120, verbose_name='День недели')),
                ('status', models.BinaryField()),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.cabinet', verbose_name='Кабинет')),
            ],
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.patient', verbose_name='Пациент'),
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='visit',
            field=models.ManyToManyField(related_name='visit_of_patient', through='hospital_app.VisitOfPatient', to='hospital_app.Visit', verbose_name='График работы'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.specialization', verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='cabinet_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.cabinetofficer', verbose_name='Ответственный за кабинет'),
        ),
    ]
