# Generated by Django 4.0 on 2022-01-25 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0003_remove_scheduleofcabinet_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalcard',
            name='visit',
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='visit',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='hospital_app.visit', verbose_name='График работы'),
        ),
        migrations.DeleteModel(
            name='VisitOfPatient',
        ),
    ]
