# Generated by Django 4.0 on 2022-01-27 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0004_remove_medicalcard_visit_medicalcard_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcard',
            name='visit',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='hospital_app.visit', verbose_name='Визит'),
        ),
    ]
