# Generated by Django 3.1.5 on 2021-01-22 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviacompany',
            name='id_workera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ФИО работника'),
        ),
        migrations.AlterField(
            model_name='dopusk',
            name='id_ekipazha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.ekipazh', verbose_name='Экипаж'),
        ),
        migrations.AlterField(
            model_name='polet',
            name='date_end_tranzit',
            field=models.DateField(blank=True, null=True, verbose_name='Дата вылета из транзита'),
        ),
        migrations.AlterField(
            model_name='polet',
            name='date_start_tranzit',
            field=models.DateField(blank=True, null=True, verbose_name='Дата транзитной посадки'),
        ),
        migrations.AlterField(
            model_name='polet',
            name='id_plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.plane', verbose_name='Самолёт'),
        ),
        migrations.AlterField(
            model_name='polet',
            name='nubmer_reysa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.reys', verbose_name='Номер-Рейс'),
        ),
        migrations.AlterField(
            model_name='polet',
            name='time_end_tranzit',
            field=models.TimeField(blank=True, null=True, verbose_name='Время вылета из транзита'),
        ),
        migrations.AlterField(
            model_name='polet',
            name='time_start_tranzit',
            field=models.TimeField(blank=True, null=True, verbose_name='Время транзитной посадки'),
        ),
        migrations.AlterField(
            model_name='razrechenie',
            name='id_ekipazha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.ekipazh', verbose_name='Экипаж'),
        ),
        migrations.AlterField(
            model_name='remont',
            name='id_plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.plane', verbose_name='Самолёт'),
        ),
    ]
