# Generated by Django 3.1.5 on 2021-01-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_auto_20210122_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polet',
            old_name='nubmer_reysa',
            new_name='number_reysa',
        ),
    ]
