version: "3"

services:
  web:
    command: bash -c "python entrypoint.py && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app/
    ports:
      - 8000:8000

  db:
    ports:
      - 5432:5432
