site_name: My docs
nav:
 - Home: index.md
 - Endpoints:
     - "Client": endpoint/client.md
     - "ServicePL": endpoint/services_pl.md
     - "MaterialsPL": endpoint/materials_pl.md
     - "Executor": endpoint/executor.md
     - "Request": endpoint/request.md
     - "Chosen Services": endpoint/chosen_services.md
     - "Chosen Materials": endpoint/chosen_materials.md
     - "Work Group": endpoint/work_group.md
     - "Invoice": endpoint/invoice.md
     - "Payment Order": endpoint/payment_order.md

theme:
 name: material