# Generated by Django 3.2.8 on 2021-12-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_auto_20211208_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='books_total',
        ),
        migrations.AddField(
            model_name='report',
            name='books_by_hall',
            field=models.IntegerField(blank=True, null=True, verbose_name='Число книг в зале'),
        ),
    ]
