# Generated by Django 3.2.8 on 2021-10-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_license',
            name='kind',
            field=models.CharField(choices=[('1', 'STANDARD'), ('2', 'FEDERAL'), ('3', 'MINISTRY OF INTERNAL AFFAIRS'), ('4', 'DIPLOMATIC'), ('5', 'ARMED'), ('6', 'ROUTE VEHICLE'), ('7', 'EXPORTED')], max_length=10),
        ),
    ]
