# Generated by Django 3.2.8 on 2021-10-30 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_auto_20211028_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='member',
        ),
    ]
