# Generated by Django 4.0 on 2021-12-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='beginning_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='ending_date',
            field=models.DateTimeField(null=True),
        ),
    ]
