# Generated by Django 4.0 on 2021-12-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_comment_beginning_date_comment_ending_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='beginning_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='ending_date',
        ),
    ]
