# Generated by Django 4.0 on 2021-12-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_alter_comment_rate_alter_tourist_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
