# Generated by Django 4.0 on 2021-12-19 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0008_country_remove_comment_title_remove_tour_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='country',
        ),
        migrations.AddField(
            model_name='tour',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tourism.country'),
        ),
    ]
