# Generated by Django 4.0 on 2021-12-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0009_remove_tour_country_tour_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
