# Generated by Django 4.0 on 2021-12-19 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0010_alter_tour_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tourism.country'),
        ),
    ]
