# Generated by Django 4.0 on 2021-12-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0012_alter_tour_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
