# Generated by Django 3.2.9 on 2021-11-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='owners',
            field=models.ManyToManyField(through='project_first_app.OwnerShip', to='project_first_app.CarOwner'),
        ),
    ]
