# Generated by Django 3.0.6 on 2020-10-03 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201003_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='highest_bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='highest_bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
