# Generated by Django 4.0 on 2021-12-25 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warriors_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warrior',
            old_name='skill',
            new_name='skills',
        ),
    ]
