# Generated by Django 3.2.8 on 2021-10-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='member',
            field=models.ManyToManyField(through='project_first_app.Owner', to='project_first_app.Car_Owner'),
        ),
    ]
