# Generated by Django 3.2.8 on 2021-10-30 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0005_auto_20211030_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_owner',
            name='address',
        ),
        migrations.RemoveField(
            model_name='car_owner',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='car_owner',
            name='passport',
        ),
    ]
