# Generated by Django 4.0.1 on 2022-01-24 07:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favouritecity',
            unique_together={('city', 'user')},
        ),
    ]
