# Generated by Django 3.2.8 on 2021-10-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_auto_20211019_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='owneruser',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='owneruser',
            name='nationality',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='owneruser',
            name='passport',
            field=models.IntegerField(null=True),
        ),
    ]
