# Generated by Django 3.0.6 on 2020-05-30 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0003_auto_20200523_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='shared',
            field=models.ManyToManyField(related_name='shared_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
