# Generated by Django 3.2.9 on 2022-01-14 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0002_reservation_user'),
        ('comments', '0004_auto_20220114_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reservation',
        ),
        migrations.AddField(
            model_name='comment',
            name='arrival',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='departure',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.room'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
