# Generated by Django 3.2.8 on 2021-10-28 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_alter_result_race'),
        ('comments', '0003_comment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='races.race'),
        ),
    ]
