# Generated by Django 3.2.10 on 2021-12-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_comment_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
    ]
