site_name: "SuperWeather Docs"
site_description: "SuperWeather - Погода в любой точке мира"

nav:
  - Главная: index.md
  - Компоненты:
    - Поле формы: input-component.md
    - Навбар: navbar.md
    - Карточка погоды в городе: weather-card.md
  - Страницы: pages.md
  - Vuex Store: store.md

theme:
  name: 'material'
  language: "ru"


markdown_extensions:
  - codehilite:
      guess_lang: false
      linenums: true


extra_css:
  - styles.css
