# Generated by Django 3.2.8 on 2021-11-29 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_remove_student_students_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.room'),
        ),
    ]
