# Generated by Django 3.2.8 on 2021-11-29 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_grades_quarter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grades_id',
        ),
        migrations.RemoveField(
            model_name='studentsgroup',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school_app.studentsgroup'),
            preserve_default=False,
        ),
    ]
