# Generated by Django 3.2.8 on 2021-11-29 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_auto_20211129_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.studentsgroup'),
        ),
    ]
