# Generated by Django 3.2.9 on 2021-12-03 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0009_auto_20211202_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='group_id',
        ),
        migrations.AddField(
            model_name='timetable',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.studentsgroup'),
        ),
    ]
