# Generated by Django 3.2.9 on 2022-01-24 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0010_auto_20211203_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.groups'),
        ),
    ]
