# Generated by Django 3.2.11 on 2022-01-24 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('local_names', models.JSONField()),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='WeatherCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.FloatField()),
                ('sunrise', models.FloatField(blank=True, null=True)),
                ('sunset', models.FloatField(blank=True, null=True)),
                ('temp', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('dew_point', models.FloatField()),
                ('uvi', models.FloatField()),
                ('clouds', models.FloatField()),
                ('visibility', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_deg', models.FloatField()),
                ('weather', models.JSONField()),
                ('wind_gust', models.FloatField(blank=True, null=True)),
                ('pop', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Текущий прогноз',
                'verbose_name_plural': 'Текущие прогнозы',
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('timezone', models.CharField(max_length=128)),
                ('timezone_offset', models.IntegerField()),
                ('minutely', models.JSONField()),
                ('hourly', models.JSONField()),
                ('alerts', models.JSONField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.city')),
                ('current', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast', to='weather.weathercurrent')),
            ],
            options={
                'verbose_name': 'Прогноз',
                'verbose_name_plural': 'Прогнозы',
            },
        ),
        migrations.CreateModel(
            name='WeatherDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField()),
                ('dt', models.FloatField()),
                ('sunrise', models.FloatField()),
                ('sunset', models.FloatField()),
                ('moonrise', models.FloatField()),
                ('moonset', models.FloatField()),
                ('moon_phase', models.FloatField()),
                ('temp', models.JSONField()),
                ('feels_like', models.JSONField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('dew_point', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_deg', models.FloatField()),
                ('wind_gust', models.FloatField()),
                ('weather', models.JSONField()),
                ('clouds', models.FloatField()),
                ('pop', models.FloatField()),
                ('snow', models.FloatField(blank=True, null=True)),
                ('uvi', models.FloatField()),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily', to='weather.weatherforecast')),
            ],
            options={
                'verbose_name': 'Прогноз по дням',
                'verbose_name_plural': 'Прогнозы по дням',
            },
        ),
    ]
