# Generated by Django 3.2.11 on 2022-01-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_ru',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
