# Generated by Django 3.2.11 on 2022-01-24 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_city_name_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecast',
            name='current',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forecast', to='weather.weathercurrent'),
        ),
    ]
