# Generated by Django 3.2.11 on 2022-01-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_favoritecity'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathercurrent',
            name='snow',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
