# Generated by Django 3.2.11 on 2022-01-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_weathercurrent_snow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecast',
            name='alerts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
