# Generated by Django 3.2.8 on 2021-10-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='name',
            field=models.CharField(default='Race', max_length=50),
            preserve_default=False,
        ),
    ]
