# Generated by Django 3.2.8 on 2021-10-30 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('races', '0003_alter_result_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='racers',
            field=models.ManyToManyField(related_name='races', to=settings.AUTH_USER_MODEL),
        ),
    ]
