# Generated by Django 3.2 on 2022-03-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuweather_app', '0002_city_favouritecity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavouriteCity',
            new_name='Favourite',
        ),
        migrations.AlterModelOptions(
            name='favourite',
            options={'verbose_name': 'Favourite', 'verbose_name_plural': 'Favourites'},
        ),
    ]
