# Generated by Django 3.1.5 on 2021-01-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20210129_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(default='tour_name', max_length=30, unique=True),
        ),
    ]
