# Generated by Django 3.1.5 on 2021-01-29 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20210129_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userscomments',
            old_name='tour',
            new_name='commented_tour',
        ),
        migrations.RenameField(
            model_name='userscomments',
            old_name='user',
            new_name='commenting_user',
        ),
    ]
