# Generated by Django 3.1.5 on 2021-01-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20210129_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userscomments',
            old_name='commented_tour',
            new_name='tour',
        ),
        migrations.AddField(
            model_name='userscomments',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userscomments',
            name='rate',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
    ]
