# Generated by Django 3.1.5 on 2021-01-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_auto_20210129_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscomments',
            name='created',
        ),
    ]
