# Generated by Django 3.2.8 on 2021-10-27 21:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_number', models.CharField(default='-', max_length=15, verbose_name='Гос номер')),
                ('brand', models.CharField(default='-', max_length=20, verbose_name='Марка')),
                ('model', models.CharField(default='-', max_length=20, verbose_name='Модель')),
                ('color', models.CharField(default='-', max_length=30, verbose_name='Цвет')),
            ],
        ),
        migrations.RemoveField(
            model_name='owner',
            name='date_b',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='date_c',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='name',
        ),
        migrations.AddField(
            model_name='owner',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='owner',
            name='first_name',
            field=models.CharField(default='-', max_length=30, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='owner',
            name='last_name',
            field=models.CharField(default='-', max_length=30, verbose_name='Фамилия'),
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания')),
                ('id_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.car')),
                ('id_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.owner')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=10, verbose_name='Номер удостоверения')),
                ('type', models.CharField(default='-', max_length=10, verbose_name='Тип')),
                ('date_of_issue', models.DateField(default=django.utils.timezone.now, verbose_name='Дата выдачи')),
                ('id_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.owner')),
            ],
        ),
    ]
