# Generated by Django 3.2.8 on 2021-10-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_auto_20211028_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='members',
            field=models.ManyToManyField(through='project_first_app.Ownership', to='project_first_app.Owner'),
        ),
    ]
