# Generated by Django 3.2.8 on 2021-10-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_car_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='description',
            field=models.TextField(default='-'),
        ),
    ]
