# Generated by Django 3.2.8 on 2021-12-02 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0008_auto_20211202_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.studentsgroup'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='room_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.room'),
        ),
    ]
