# Generated by Django 3.2.9 on 2021-12-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20211202_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
