# Generated by Django 3.2.9 on 2021-12-02 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_floor_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id_floor',
        ),
        migrations.AddField(
            model_name='floor',
            name='id_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
        ),
    ]
