# Generated by Django 3.2.9 on 2021-12-02 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20211202_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='id_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.bill'),
        ),
    ]
