# Generated by Django 3.2.9 on 2021-12-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_floor_id_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='id_client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='id_room',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='floor',
            old_name='id_room',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='id_client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='id_employee',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='id_employee',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='id_room',
            new_name='room',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='id_bill',
        ),
    ]
