# Generated by Django 3.2.9 on 2021-12-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_auto_20211202_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.SmallIntegerField(default='1'),
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
    ]
