# Generated by Django 3.2.8 on 2021-10-30 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('races', '0004_alter_race_racers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='racers',
            field=models.ManyToManyField(null=True, related_name='races', to=settings.AUTH_USER_MODEL),
        ),
    ]
