# Generated by Django 3.2.8 on 2021-12-02 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_auto_20211202_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='students_group_id',
        ),
        migrations.AddField(
            model_name='timetable',
            name='group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school_app.groups'),
            preserve_default=False,
        ),
    ]
