# Generated by Django 3.2.11 on 2022-01-21 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0010_auto_20211203_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.groups'),
        ),
    ]
