# Generated by Django 3.2.8 on 2021-10-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='last_submission',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
