# Generated by Django 3.2.8 on 2021-10-22 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('deadline', models.DateTimeField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.discipline')),
            ],
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'classes'},
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(blank=True, max_length=500)),
                ('grade', models.IntegerField(blank=True, choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Fair'), (2, 'Poor')], null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.student')),
            ],
        ),
    ]
