# Generated by Django 3.2.8 on 2021-10-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20211022_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.CharField(default='HW1', max_length=30),
            preserve_default=False,
        ),
    ]
