# Generated by Django 3.2.8 on 2021-10-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_submission_last_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='last_submission',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
