# Generated by Django 3.2.8 on 2021-10-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20211023_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='deadline',
        ),
        migrations.AddField(
            model_name='submission',
            name='deadline',
            field=models.DateTimeField(default='2021-12-31'),
            preserve_default=False,
        ),
    ]
