# Generated by Django 3.2.8 on 2021-10-24 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20211023_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='board.teacher'),
            preserve_default=False,
        ),
    ]
