# Generated by Django 3.2.8 on 2021-10-24 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_assignment_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignment',
            new_name='Task',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='assignment',
            new_name='task',
        ),
    ]
