# Generated by Django 3.2.8 on 2021-10-24 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20211024_2202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submission',
            new_name='Assignment',
        ),
    ]
