# Generated by Django 3.2.8 on 2021-10-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20211026_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='grade_comment',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
