# Generated by Django 3.2.8 on 2021-10-27 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_assignment_grade_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='last_submission',
            new_name='last_changed',
        ),
    ]
