# Generated by Django 3.2.8 on 2021-10-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('COOP', 'Cooperation issue'), ('RACE', 'Racing question'), ('OTHER', 'Other')], default='COOP', max_length=15),
            preserve_default=False,
        ),
    ]
