# Generated by Django 4.0 on 2022-01-04 10:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import hotel_app.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_host', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('place_type', models.CharField(choices=[('1', 'Apartment'), ('2', 'House'), ('3', 'Secondary unit'), ('4', 'Unique space'), ('5', 'Boutique hotel'), ('6', 'Bed and breakfast')], default=1, max_length=1)),
                ('place_offers', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Kitchen'), ('2', 'Wifi'), ('3', 'Free parking on premises'), ('4', 'Pets allowed'), ('5', 'Hair dryer'), ('6', 'Shampoo'), ('7', 'Body soap'), ('8', 'Hot water'), ('9', 'Body Washer'), ('10', 'Bed linens'), ('11', 'Smoke alarm'), ('12', 'Cooking basics'), ('13', 'TV'), ('14', 'Air conditioning'), ('15', 'Heating'), ('16', 'Private entrance')], max_length=38)),
                ('desc', models.CharField(max_length=1000)),
                ('beds', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('guests', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to=hotel_app.models.upload_path)),
                ('price', models.IntegerField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=1000)),
                ('review_date', models.DateField(auto_now_add=True)),
                ('value', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.user')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.place')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('guests_count', models.IntegerField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.user')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.place')),
            ],
        ),
    ]
