# Generated by Django 3.2.9 on 2021-11-30 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0002_auto_20211130_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.CreateModel(
            name='StudentToGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(through='college_app.StudentToGroup', to='college_app.Group'),
        ),
    ]
