# Generated by Django 3.2.9 on 2021-11-30 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0003_auto_20211130_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.group'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='name_day',
            field=models.CharField(choices=[('Mon', 'Понедельник'), ('Tue', 'Вторник'), ('Wed', 'Среда'), ('Thu', 'Четверг'), ('Fri', 'Пятница'), ('Sat', 'Суббота'), ('Sun', 'Воскресенье')], max_length=30),
        ),
    ]
