# Generated by Django 4.0 on 2021-12-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home4night', '0004_alter_review_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Cancelled'), (0, 'Unpaid'), (1, 'Paid')]),
        ),
    ]
