# Generated by Django 3.2.9 on 2022-01-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historybill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('hotel_name', models.CharField(max_length=500)),
                ('adress_hotel', models.CharField(max_length=500)),
                ('money', models.IntegerField()),
            ],
        ),
    ]
