# Generated by Django 4.0.1 on 2022-01-27 15:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0002_flightbookings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlightBookings',
            new_name='FlightBooking',
        ),
    ]
