# Generated by Django 3.2.8 on 2021-11-09 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='id_tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tours_app.tours'),
            preserve_default=False,
        ),
    ]
