# Generated by Django 3.2.8 on 2021-11-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours_app', '0002_reviews_id_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tours',
            name='status',
        ),
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.CharField(choices=[('A', 'confirmed'), ('B', 'not confirmed')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
