# Generated by Django 3.2.8 on 2021-11-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours_app', '0003_auto_20211109_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('not confirmed', 'not confirmed')], max_length=30),
        ),
    ]
