# Generated by Django 3.2.8 on 2021-11-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours_app', '0006_auto_20211111_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rate',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]),
        ),
    ]
