# Generated by Django 3.2.8 on 2021-11-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='doc_data',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='users',
            name='f_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
