# Generated by Django 3.2.11 on 2022-01-23 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='ID чека')),
                ('qr_data', models.CharField(blank=True, max_length=100, null=True, verbose_name='Данные QR кода')),
                ('name', models.CharField(max_length=1000, verbose_name='Наименование')),
                ('address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Адрес')),
                ('date', models.DateTimeField(verbose_name='Дата покупки')),
                ('total_sum', models.PositiveIntegerField(verbose_name='Сумма чека')),
                ('fn', models.CharField(blank=True, help_text='Номер фискального накопителя', max_length=20, null=True, verbose_name='ФН')),
                ('fp', models.CharField(blank=True, help_text='Фискальный признак документа', max_length=20, null=True, verbose_name='ФПД')),
                ('fd', models.CharField(blank=True, help_text='Номер фискального документа', max_length=20, null=True, verbose_name='ФД')),
                ('org_inn', models.CharField(max_length=20, verbose_name='ИНН организации')),
                ('org_name', models.CharField(max_length=20, verbose_name='Название организации')),
                ('org_address', models.CharField(blank=True, max_length=20, null=True, verbose_name='Юр. адрес организации')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts_receipt_created', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.PROTECT, on_update=True, related_name='receipts_receipt_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлён')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='ID товара')),
                ('name', models.CharField(max_length=1000, verbose_name='Наименование')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='Количество')),
                ('sum', models.PositiveIntegerField(verbose_name='Сумма')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts_receiptitem_created', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='receipts.receipt', verbose_name='Чек')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.PROTECT, on_update=True, related_name='receipts_receiptitem_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлён')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='HistoricalReceiptItem',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления')),
                ('id', models.PositiveBigIntegerField(db_index=True, verbose_name='ID товара')),
                ('name', models.CharField(max_length=1000, verbose_name='Наименование')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='Количество')),
                ('sum', models.PositiveIntegerField(verbose_name='Сумма')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='receipts.receipt', verbose_name='Чек')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.DO_NOTHING, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлён')),
            ],
            options={
                'verbose_name': 'История изменений',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalReceipt',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления')),
                ('id', models.PositiveBigIntegerField(db_index=True, verbose_name='ID чека')),
                ('qr_data', models.CharField(blank=True, max_length=100, null=True, verbose_name='Данные QR кода')),
                ('name', models.CharField(max_length=1000, verbose_name='Наименование')),
                ('address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Адрес')),
                ('date', models.DateTimeField(verbose_name='Дата покупки')),
                ('total_sum', models.PositiveIntegerField(verbose_name='Сумма чека')),
                ('fn', models.CharField(blank=True, help_text='Номер фискального накопителя', max_length=20, null=True, verbose_name='ФН')),
                ('fp', models.CharField(blank=True, help_text='Фискальный признак документа', max_length=20, null=True, verbose_name='ФПД')),
                ('fd', models.CharField(blank=True, help_text='Номер фискального документа', max_length=20, null=True, verbose_name='ФД')),
                ('org_inn', models.CharField(max_length=20, verbose_name='ИНН организации')),
                ('org_name', models.CharField(max_length=20, verbose_name='Название организации')),
                ('org_address', models.CharField(blank=True, max_length=20, null=True, verbose_name='Юр. адрес организации')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.DO_NOTHING, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлён')),
            ],
            options={
                'verbose_name': 'История изменений',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
