site_name: Прогноз погоды

nav:
  - "О проекте":
      - "Цели и задачи": "about_1.md"
      - "Средства разработки": "about_2.md"
      - "Функциональные требования": "about_3.md"
  - "Страницы сервиса": "pages.md"
  - "Запуск проекта": "startup.md"
  - "Структура проекта": "structure.md"



theme:
  name: windmill

