# Generated by Django 3.1.5 on 2021-01-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_auto_20210125_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='driver',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
