# Generated by Django 3.2.9 on 2022-01-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worriors_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worrior',
            new_name='Warrior',
        ),
    ]
