# Generated by Django 2.2.2 on 2021-10-30 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Racers',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=50)),
                ('car', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RaceRacers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('racerRate', models.IntegerField()),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raceWinners.Racers')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField()),
                ('racers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raceWinners.RaceRacers')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('comment_type', models.CharField(max_length=100)),
                ('comment_text', models.CharField(max_length=500)),
                ('rate', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raceWinners.Users')),
            ],
        ),
    ]
