site_name: Описание сервиса "Рекламное агентство Луч"
nav:
 - Home: index.md
 - Endpoints:
     - "Client endpoints": endpoint/client.md
     - "ServicePL endpoints": endpoint/services_pl.md
     - "MaterialsPL endpoints": endpoint/materials_pl.md
     - "Executor endpoints": endpoint/executor.md
     - "Request endpoints": endpoint/request.md
     - "Chosen Services endpoints": endpoint/chosen_services.md
     - "Chosen Materials endpoints": endpoint/chosen_materials.md
     - "Work Group endpoints": endpoint/work_group.md
     - "Invoice endpoints": endpoint/invoice.md
     - "Payment Order endpoints": endpoint/payment_order.md
 - Interfaces Overview: interfaces/overview.md
 - Interfaces:
     - "SignUp": interfaces/sign_up.md
     - "SignIn": interfaces/sign_in.md
     - "Account Details": interfaces/account_details.md
     - "Client": interfaces/client.md
     - "ServicePL": interfaces/services_pl.md
     - "MaterialsPL": interfaces/materials_pl.md
     - "Executor": interfaces/executor.md
     - "Request": interfaces/request.md
     - "Chosen Services": interfaces/chosen_services.md
     - "Chosen Materials": interfaces/chosen_materials.md
     - "Work Group": interfaces/work_group.md
     - "Invoice": interfaces/invoice.md
     - "Payment Order": interfaces/payment_order.md

theme:
 name: material