# Generated by Django 3.2.8 on 2021-11-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_car_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
