version: '3'

volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aviatickets
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: django
    build: ./aviatickets
    command: python manage.py runserver
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./aviatickets:/aviatickets
