# Generated by Django 3.2.10 on 2022-09-03 17:29

import ad_agency.models
import ad_agency.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_agency', '0003_auto_20220831_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialsPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50, verbose_name='Имя файла')),
                ('size', models.IntegerField(verbose_name='Размер файла')),
                ('file', models.FileField(upload_to=ad_agency.models.get_upload_path, validators=[ad_agency.validators.validate_file_size, ad_agency.validators.validate_file_type])),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_agency.materialspl', verbose_name='Материал')),
            ],
        ),
    ]
