# Generated by Django 3.2.10 on 2022-09-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_agency', '0005_auto_20220903_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='old_phone',
        ),
    ]
