# Generated by Django 3.2.10 on 2022-09-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_agency', '0006_remove_client_old_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='old_phone',
            field=models.CharField(blank=True, max_length=12, verbose_name='Старый номер телефона'),
        ),
    ]
