# Generated by Django 3.2.10 on 2022-09-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_agency', '0007_client_old_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='old_phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
