# Generated by Django 4.0.1 on 2022-01-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='date',
        ),
    ]
