# Generated by Django 3.2.11 on 2022-01-18 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warriors_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warrior',
            old_name='skill',
            new_name='skills',
        ),
    ]
