# Generated by Django 4.0 on 2022-01-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home4night', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Cancelled'), (0, 'Unpaid'), (1, 'Paid')], default=0),
        ),
    ]
