# Generated by Django 4.0 on 2022-01-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home4night', '0007_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID'), ('CANCELLED', 'CANCELLED')], default='Unpaid', max_length=10),
        ),
    ]
