# Generated by Django 4.0 on 2022-01-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home4night', '0008_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='last_changed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
