# Generated by Django 4.0 on 2022-01-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home4night', '0009_review_last_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID'), ('CANCELLED', 'CANCELLED')], default='UNPAID', max_length=10),
        ),
    ]
