# Generated by Django 3.2.9 on 2021-11-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.IntegerField(default='0'),
        ),
    ]
