# Generated by Django 3.2.9 on 2022-01-15 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200, verbose_name='Название книги')),
                ('authors', models.CharField(max_length=500, verbose_name='Автор(ы)')),
                ('publisher', models.CharField(max_length=200, verbose_name='Издательство')),
                ('pub_year', models.DateField(verbose_name='Год публикации')),
                ('section', models.CharField(max_length=20, verbose_name='Раздел')),
                ('instance_count', models.IntegerField(max_length=10, verbose_name='Количество экземпляров в библиотеке')),
                ('bk_cipher', models.CharField(max_length=10, verbose_name='Шифр книги')),
            ],
        ),
        migrations.CreateModel(
            name='BookAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach_date', models.DateTimeField(verbose_name='Дата закрепления')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.book', verbose_name='Название книги')),
            ],
        ),
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_num', models.IntegerField(max_length=2, verbose_name='Номер зала')),
                ('hall_name', models.CharField(max_length=300, verbose_name='Название зала')),
                ('capacity', models.IntegerField(max_length=4, verbose_name='Вместимость')),
            ],
        ),
        migrations.CreateModel(
            name='Readers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_ticket_number', models.IntegerField(max_length=8, verbose_name='Номер читательского билета')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('passport', models.CharField(max_length=10, unique=True, verbose_name='Номер паспорта')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='Номер телефона')),
                ('education', models.CharField(choices=[('b', 'начальное'), ('m', 'среднее'), ('h', 'высшее')], max_length=1, verbose_name='Образование')),
                ('scientist', models.CharField(choices=[('1', 'есть'), ('0', 'нет')], max_length=1, verbose_name='Наличие ученной степени')),
                ('attached_books', models.ManyToManyField(blank=True, null=True, through='library_app.BookAttachment', to='library_app.Book', verbose_name='Закрепленные книги')),
            ],
        ),
        migrations.CreateModel(
            name='ReaderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach_date', models.DateTimeField(verbose_name='Дата закрепления читателя')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.halls', verbose_name='Название зала')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.readers', verbose_name='ФИО читателя')),
            ],
        ),
        migrations.AddField(
            model_name='bookattachment',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.readers', verbose_name='ФИО читателя'),
        ),
    ]
