# Generated by Django 3.2.9 on 2022-01-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='book',
            name='instance_count',
            field=models.IntegerField(verbose_name='Количество экземпляров в библиотеке'),
        ),
        migrations.AlterField(
            model_name='halls',
            name='capacity',
            field=models.IntegerField(verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='halls',
            name='hall_num',
            field=models.IntegerField(verbose_name='Номер зала'),
        ),
        migrations.AlterField(
            model_name='readers',
            name='attached_books',
            field=models.ManyToManyField(blank=True, through='library_app.BookAttachment', to='library_app.Book', verbose_name='Закрепленные книги'),
        ),
        migrations.AlterField(
            model_name='readers',
            name='reader_ticket_number',
            field=models.IntegerField(verbose_name='Номер читательского билета'),
        ),
    ]
