# Generated by Django 3.2.9 on 2022-01-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_auto_20220117_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
