# Generated by Django 3.2.9 on 2022-01-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
