# Generated by Django 3.2.11 on 2022-01-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='check_scan_token',
            field=models.TextField(blank=True, null=True, verbose_name='Токен ЧекСкан'),
        ),
        migrations.AddField(
            model_name='user',
            name='check_scan_token',
            field=models.TextField(blank=True, null=True, verbose_name='Токен ЧекСкан'),
        ),
    ]
