# Generated by Django 3.2.11 on 2022-01-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_checkscan_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='patronymic',
        ),
    ]
