# Generated by Django 4.0 on 2021-12-13 19:17

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Birthday', models.DateField(default=django.utils.timezone.now)),
                ('Sex', models.CharField(default='', max_length=10)),
                ('Phone', models.IntegerField(default='0')),
                ('Nationality', models.CharField(default='', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('Check_in', models.DateField(default=django.utils.timezone.now)),
                ('Check_out', models.DateField(default=django.utils.timezone.now)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_hotel', models.CharField(default='', max_length=500)),
                ('Owner', models.CharField(default='', max_length=500)),
                ('Address', models.CharField(default='', max_length=500)),
                ('Describe', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(default='0')),
                ('Type', models.CharField(default='', max_length=500)),
                ('Price', models.IntegerField(default='0')),
                ('State', models.CharField(default='', max_length=500)),
                ('Member', models.ManyToManyField(through='my_app.Bill', to=settings.AUTH_USER_MODEL)),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_hotel', models.CharField(default='', max_length=500)),
                ('Content', models.CharField(default='', max_length=500)),
                ('Check_in', models.DateField(default=django.utils.timezone.now)),
                ('Check_out', models.DateField(default=django.utils.timezone.now)),
                ('Rate', models.IntegerField(default='0')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.client')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='id_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.room'),
        ),
    ]
