# Generated by Django 3.2.9 on 2021-11-18 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_text', models.CharField(max_length=300)),
                ('description', models.TextField(null=True)),
                ('location', models.CharField(max_length=30)),
                ('description_location', models.CharField(max_length=30)),
                ('date_start', models.DateTimeField(max_length=30)),
                ('date_end', models.DateTimeField(max_length=30)),
                ('description_conferences', models.CharField(max_length=100, verbose_name='Описание')),
                ('keyword', models.CharField(max_length=50, verbose_name='Ключевые слова')),
                ('terms_participation', models.CharField(max_length=350, verbose_name='Условия участия')),
            ],
            options={
                'verbose_name': 'Конференция',
                'verbose_name_plural': 'Конференции',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40, verbose_name='Тема выступления')),
                ('result', models.BooleanField(default=False, verbose_name='Рекомендован к публикации')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('conference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_conference_app.conference')),
                ('topics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_conference_app.topic', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Выступление',
                'verbose_name_plural': 'Выступления',
            },
        ),
        migrations.AddField(
            model_name='conference',
            name='topics',
            field=models.ManyToManyField(null=True, to='project_conference_app.Topic', verbose_name='топики'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
                ('moderation', models.BooleanField(default=False, verbose_name='Модерация')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_conference_app.conference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
            },
        ),
    ]
