# Generated by Django 3.2.9 on 2021-11-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_conference_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='topics',
            field=models.ManyToManyField(to='project_conference_app.Topic', verbose_name='топики'),
        ),
    ]
