# Generated by Django 3.2.9 on 2021-11-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
