# Generated by Django 3.2.9 on 2021-11-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_alter_owner_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='owners',
        ),
    ]
