# Generated by Django 3.2.8 on 2021-12-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airlineadministration',
            name='crew_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='in_crew',
        ),
        migrations.AddField(
            model_name='employee',
            name='in_crew',
            field=models.IntegerField(default=0, verbose_name='Состоит в экипаже под номером'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='crew',
            field=models.IntegerField(verbose_name='Экипаж на борту'),
        ),
        migrations.AlterField(
            model_name='flightasscheduled',
            name='distance',
            field=models.IntegerField(verbose_name='Расстояние до пункта назначения в км'),
        ),
        migrations.AlterField(
            model_name='flightasscheduled',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Номер рейса'),
        ),
        migrations.DeleteModel(
            name='Crew',
        ),
    ]
