# Generated by Django 3.2.9 on 2021-11-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_app', '0003_alter_reservation_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='approval',
            field=models.CharField(choices=[('Заселен', 'Заселен'), ('Не заселен', 'Не заселен')], default='Не заселен', max_length=10),
        ),
    ]
