# Generated by Django 3.2.9 on 2021-11-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_app', '0004_alter_reservation_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='check_in_date',
            field=models.DateField(default='2021-01-01'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_out_date',
            field=models.DateField(default='2021-01-01'),
        ),
    ]
