# Generated by Django 3.2.9 on 2021-11-21 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_app', '0005_auto_20211121_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='hotel',
        ),
        migrations.AddField(
            model_name='review',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels_app.reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='approval',
            field=models.CharField(choices=[('Подтверждена', 'Подтверждена'), ('Не рассмотрена', 'Не рассмотрена'), ('Заселен', 'Заселен')], default='Не рассмотрена', max_length=15),
        ),
    ]
