# Generated by Django 3.2.9 on 2021-12-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_app', '0008_auto_20211203_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reservation',
        ),
    ]
