# Generated by Django 4.0 on 2021-12-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': 'Host'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': 'Visitor'},
        ),
        migrations.AlterField(
            model_name='hoteluser',
            name='sex',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('N', 'N/A')], max_length=10, verbose_name='Sex'),
        ),
    ]
