# Generated by Django 4.0 on 2021-12-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_alter_hoteluser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='state',
            field=models.CharField(choices=[('AV', 'Available'), ('NA', 'Not Available'), ('MA', 'On maintainence')], max_length=500, verbose_name='State'),
        ),
    ]
