# Generated by Django 4.0 on 2021-12-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0004_alter_room_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='total',
            field=models.IntegerField(default='0', verbose_name='Total Cost of Service'),
        ),
    ]
