# Generated by Django 4.0 on 2021-12-26 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0005_bill_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='id_hotel',
            new_name='hotel',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='id_booking',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='id_main_guest',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='id_room',
        ),
        migrations.AddField(
            model_name='bill',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bills', to='hotel_app.booking', verbose_name='Booking Id'),
        ),
        migrations.AddField(
            model_name='booking',
            name='main_guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to='hotel_app.visitor', verbose_name='Main guest'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_app.room', verbose_name='Room'),
        ),
    ]
