# Generated by Django 4.0 on 2021-12-27 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0006_rename_id_hotel_room_hotel_remove_bill_id_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel_app.hotel', verbose_name='Hotel Id'),
        ),
    ]
