# Generated by Django 3.2.12 on 2022-03-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cage',
            name='shed',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Shed',
        ),
    ]
