# Generated by Django 3.2.12 on 2022-03-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_auto_20220308_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='salary',
        ),
    ]
