site_name: Описание сервиса "Войны"
nav:
  - Home: index.md
  - Professions:
    - "mining engineering": professions/mining_engineering.md
    - "picking herbs": professions/picking_herbs.md
  - Api:
    - "api/warriors[GET]": api/warriors.md

theme:
 name: material
