# Generated by Django 3.2.8 on 2021-10-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oweruser',
            name='tester',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
