# Generated by Django 3.2.8 on 2021-10-31 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_oweruser_tester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oweruser',
            name='tester',
        ),
    ]
