# Generated by Django 3.2.12 on 2022-02-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '01_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
