# Generated by Django 4.0.1 on 2022-02-09 12:35

from django.db import migrations, models
import weather.fields


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='days_count',
            field=weather.fields.IntegerRangeField(default=3),
        ),
        migrations.AlterField(
            model_name='continent',
            name='continent_name',
            field=models.CharField(choices=[(1, 'Asia'), (2, 'Europe'), (3, 'North America'), (4, 'South America'), (5, 'Oceania'), (6, 'Africa')], max_length=10),
        ),
    ]
