# Generated by Django 4.0 on 2021-12-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0004_user_alter_owner_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
