# Generated by Django 4.0 on 2021-12-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0006_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
