# Generated by Django 4.0 on 2021-12-08 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0007_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_first_app.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
