# Generated by Django 3.2.10 on 2021-12-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0005_alter_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='Floor'),
        ),
    ]
